LibraryProject/LibraryProject/Controllers/BookController.cs
using Library.Data.Model;
using Library.Data.UnitOfWork;
using LibraryProject.SupporterClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryProject.Controllers
{
    [RoleControl]
    public class BookController : Controller
    {
        // GET: Book
        UnitOfWork unitofWork;
        public BookController()
        {
            unitofWork = new UnitOfWork();
        }
        public ActionResult Index()
        {
            var books = unitofWork.GetRepository<Book>().GetAll();
            return View(books);
        }

        public ActionResult AddBook()
        {
            ViewBag.Categories = unitofWork.GetRepository<Category>().GetAll();
            ViewBag.Writers = unitofWork.GetRepository<Writer>().GetAll();
            return View();
        }
        
        [HttpPost]
        public JsonResult AddBookJson(string[] categoriess, string writer, string bookName, string numOfBook, string rowOfBook)
        {
            if (categoriess != null && !string.IsNullOrEmpty(writer) && !string.IsNullOrEmpty(bookName) && !string.IsNullOrEmpty(numOfBook) && !string.IsNullOrEmpty(rowOfBook))
            {
                List<Category> lstCtg = new List<Category>();
                foreach (var ctgIds in categoriess)
                {
                    var categoryId = Convert.ToInt32(ctgIds);
                    var ctg = unitofWork.GetRepository<Category>().GetById(categoryId);
                    lstCtg.Add(ctg);
                }
                Book book = new Book(); //gelen verileri ekledik
                book.Name = bookName;
                book.Number = Convert.ToInt32(numOfBook);
                book.WriterId = Convert.ToInt32(writer);
                book.RowNumber = rowOfBook;
                book.Categories = lstCtg;
                book.DateOfUpload = DateTime.Now;
                unitofWork.GetRepository<Book>().Add(book); //kitabı ekledik

                var situation = unitofWork.SaveChanges();//kaydettik
                if (situation > 0)
                {
                    return Json("1");
                }
                else
                {
                    return Json("0");
                }
            }
            else
            {
                return Json("notNull"); //bos olamaz diye uyari vericek
            }
        }


        [HttpPost]
        public JsonResult DeleteJson(int bookId)
        {
            unitofWork.GetRepository<Book>().Delete(bookId);
            var situation = unitofWork.SaveChanges();//kaydettik
            if (situation > 0)
            {
                return Json("1");
            }
            else
            {
                return Json("0");
            }
        }

        public ActionResult Update(int bookId)
        {
            ViewBag.Categories = unitofWork.GetRepository<Category>().GetAll();
            ViewBag.Writers = unitofWork.GetRepository<Writer>().GetAll();
            var book = unitofWork.GetRepository<Book>().GetById(bookId);
            return View(book);
        }
        
        [HttpPost]
        public JsonResult UpdateBookJson(int bookId, string[] categoriess, string writer, string bookName, string numOfBook, string rowOfBook)
        {
            if (categoriess != null && !string.IsNullOrEmpty(writer) && !string.IsNullOrEmpty(bookName) && !string.IsNullOrEmpty(numOfBook) && !string.IsNullOrEmpty(rowOfBook))
            {
                List<Category> lstCtg = new List<Category>();
                foreach (var ctgIds in categoriess)
                {
                    var categoryId = Convert.ToInt32(ctgIds);
                    var ctg = unitofWork.GetRepository<Category>().GetById(categoryId);
                    lstCtg.Add(ctg);
                }
                var book = unitofWork.GetRepository<Book>().GetById(bookId); //kitap id gönderdik veriyi aldık altta değiştirdik
                book.Name = bookName;
                book.Number = Convert.ToInt32(numOfBook);
                book.WriterId = Convert.ToInt32(writer);
                book.RowNumber = rowOfBook;
                book.Categories.Clear();//veri eklemeden önce içeridekileri sildik kod throw'a düşüyordu
                book.Categories = lstCtg;

                unitofWork.GetRepository<Book>().Update(book); //kitabı editledik

                var situation = unitofWork.SaveChanges();//kaydettik
                if (situation > 0)
                {
                    return Json("1");
                }
                else
                {
                    return Json("0");
                }
            }
            else
            {
                return Json("notNull"); //bos olamaz diye uyari vericek
            }
        }
    }
}

LibraryProject/LibraryProject/Controllers/LoginController.cs
using Library.Data.HelperClass;
using Library.Data.Model;
using Library.Data.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryProject.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        private readonly UnitOfWork _unitofWork;
        public LoginController()
        {
            _unitofWork = new UnitOfWork();
        }
        public ActionResult Index()
        {
            if (Request.Cookies["member"] != null) //kullanıcı giriş yapmışsa ve tekrar logine dönerse?
            {
                return RedirectToAction("Index","Book");
            }
            
            return View();
        }

        [HttpPost]
        public JsonResult LoginControl(string email, string pass, bool remember)
        {
            email = email.Trim();
            pass = pass.Trim();
            if (string.IsNullOrEmpty(email) && string.IsNullOrEmpty(pass))
            {
                return Json("notNull");
            }

            pass=pass.Encrypt();
            var member = new Member();

            try{ member = _unitofWork.GetRepository<Member>().Get(x => x.Mail == email && x.Pass == pass); }
            catch { }

            if (member != null)
            {
                HttpCookie cookie = new HttpCookie("member");
                cookie.Values.Add("Id", member.Id.ToString());
                cookie.Values.Add("Name", member.Name);
                cookie.Values.Add("Surname", member.Surname);
                cookie.Values.Add("RoleId", member.Role);

                if (remember) cookie.Expires = DateTime.Now.AddDays(5); //cookie 5 gün tut

                Response.Cookies.Add(cookie);

                return Json("Success");
            }
            else return Json("0");
        }

        public ActionResult Logout()
        {
            var cookie = Response.Cookies["member"];
            if (cookie !=null)
            {
                cookie.Expires = DateTime.Now.AddDays(-1);
            }

            return RedirectToAction("Index");
        }
    }
}

LibraryProject/LibraryProject/Controllers/MemberController.cs
using Library.Data.Model;
using Library.Data.UnitOfWork;
using LibraryProject.SupporterClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryProject.Controllers
{
    [RoleControl]
    public class MemberController : Controller
    {
        // GET: Member
        UnitOfWork unitofWork;
        public MemberController()
        {
            unitofWork = new UnitOfWork();
        }
        public ActionResult Index()
        {
            var members = unitofWork.GetRepository<Member>().GetAll();
            return View(members);
        }
        public ActionResult AddMember()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AddMemberJson(string memberName, string memberSurname, string memberTc, string memberPhone)
        {
            if (memberTc.Length > 11 || memberPhone.Length > 11) return Json("notNull");

            if (!string.IsNullOrEmpty(memberName) && !string.IsNullOrEmpty(memberSurname))
            {
                Member member = new Member();
                member.Name = memberName;
                member.Surname = memberSurname;
                member.TcNo = memberTc.ToString();
                member.PhoneNum = memberPhone.ToString();
                member.Punishment = 0;
                member.RegTime = DateTime.Now;
                member.Role = "3";

                unitofWork.GetRepository<Member>().Add(member);
                var situation = unitofWork.SaveChanges();
                if (situation > 0)
                    return Json("1");
                else return Json("0");
            }
            else
            {
                return Json("notNull");
            }
        }

        [HttpPost]
        public JsonResult DeleteMemberJson(int memberId)
        {
            unitofWork.GetRepository<Member>().Delete(memberId);
            var situation = unitofWork.SaveChanges();
            if (situation > 0)
            {
                return Json("1");
            }
            else
            {
                return Json("0");
            }
        }

        public ActionResult Update(int memberId) //update sayfasını döndürüyoruz
        {
            var member = unitofWork.GetRepository<Member>().GetById(memberId);
            return View(member);
        }

        [HttpPost]
        public JsonResult UpdateMemberJson(int memberId, string memberName, string memberSurname, string memberTc, string memberPhone)
        {
            if (!string.IsNullOrEmpty(memberName) && !string.IsNullOrEmpty(memberSurname))
            {
                var member = unitofWork.GetRepository<Member>().GetById(memberId);
                member.Name = memberName;
                member.Surname = memberSurname;
                member.TcNo = memberTc;
                member.PhoneNum = memberPhone;
                unitofWork.GetRepository<Member>().Update(member);
                var situation = unitofWork.SaveChanges();
                if (situation > 0)
                    return Json("1");
                else return Json("0");
            }
            else
            {
                return Json("notNull");
            }
        }
    }
}

LibraryProject/LibraryProject/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Data.Model;
using Library.Data.UnitOfWork;
using LibraryProject.SupporterClasses;

namespace LibraryProject.Controllers
{
    [RoleControl]
    public class VoteController : Controller
    {
        // GET: Vote
        readonly UnitOfWork unitofWork;
        public VoteController()
        {
            unitofWork = new UnitOfWork();
        }
        public ActionResult Index()
        {
            var voteBooks = unitofWork.GetRepository<Book>().GetAll(); //get all books
            return View(voteBooks);
        }

        [HttpPost]
        public JsonResult VoteJson(int bookId)
        {
            if (bookId == 0) { return Json("err"); }
            var updatedRate = unitofWork.GetRepository<Book>().GetById(bookId);
            updatedRate.bookRate += 1;
            var situation = unitofWork.SaveChanges();
            if (situation > 0)
                return Json("1");
            else return Json("0");
        }
    }
}

LibraryProject/LibraryProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Css/sidebar-nav.min.css" rel="stylesheet" />
    <link href="~/Content/Css/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <link href="~/Content/Css/css-chart.css" rel="stylesheet" />
    <link href="~/Content/Css/animate.css" rel="stylesheet" />
    <link href="~/Content/Css/style.css" rel="stylesheet" />
    <link href="~/Content/Css/blue.css" rel="stylesheet" />
    <link href="~/Content/Css/jquery.dataTables.min.css" rel="stylesheet" /> @*i used api from https://datatables.net/examples/api/multi_filter.html*@
    <link href="~/Content/Css/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/Css/sweetalert2.min.css" rel="stylesheet" />
    <style>
        tfoot input {
            width: 100%;
            padding: 3px;
            box-sizing: border-box;
        }
    </style>
</head>
<body>
    <div class="preloader">
        <div class="cssload-speeding-wheel"></div>
    </div>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header">
                <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>
                <div class="top-left-part">
                    <a class="logo" href="@Url.Action("Index","")">
                        <b>
                            <img src="~/Content/libraryImg/eliteadmin-logo.png" />
                        </b><span class="hidden-xs">
                            <img src="~/Content/libraryImg/eliteadmin-text.png" />
                        </span>
                    </a>
                </div>
                <ul class="nav navbar-top-links navbar-left hidden-xs">
                    <li><a href="javascript:void(0)" class="open-close hidden-xs waves-effect waves-light"><i class="icon-arrow-left-circle ti-menu"></i></a></li>
                </ul>
                <ul class="nav navbar-top-links navbar-right pull-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#"> <img src="~/Content/libraryImg/user.png" alt="user-img" width="36" class="img-circle"><b class="hidden-xs">@Request.Cookies["member"]["Name"]</b> </a>
                        <ul class="dropdown-menu dropdown-user animated flipInY">
                            <li><a href="@Url.Action("UpdateProfileInfo","Membership")"><i class="fa fa-power-off"></i> Update Profile </a></li>
                            <li><a href="@Url.Action("Logout","Login")"><i class="fa fa-power-off"></i> Logout </a></li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                </ul>
            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>
        <!-- Left navbar-header -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse slimscrollsidebar">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search hidden-sm hidden-md hidden-lg">
                        <!-- input-group -->
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button"> <i class="fa fa-search"></i> </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li class="user-pro">
                        <a href="#" class="waves-effect"><img src="~/Content/libraryImg/user.png" alt="user-img" class="img-circle"> <span class="hide-menu"> @Request.Cookies["member"]["Name"] @Request.Cookies["member"]["Surname"]<span class="fa arrow"></span></span></a>
                        <ul class="nav nav-second-level">
                            @*<li><a href="javascript:void(0)"><i class="ti-settings"></i> Account Setting</a></li>*@
                            <li><a href="@Url.Action("UpdateProfileInfo","Membership")"><i class="fa fa-power-off"></i> Update Profile </a></li>
                            <li><a href="@Url.Action("Logout","Login")"><i class="fa fa-power-off"></i> Logout </a></li>
                        </ul>
                    </li>
                    <li class="nav-small-cap m-t-10">—— MENÜLER</li>
                    <li>
                        <a href="@Url.Action("Index","Statistics")" class="waves-effect"><i class="linea-icon linea-basic fa-fw" data-icon="q"></i>Statistics</a>
                    </li>
                    <li>
                        <a href="inbox.html" class="waves-effect"><i data-icon=")" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Categories</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="@Url.Action("Index","Category")">List Categories</a></li>
                            <li><a id="btnAddCtg" class="btnAddCtg" href="javascript:void(0)">Add Category</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="inbox.html" class="waves-effect"><i data-icon=")" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Writers </span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="@Url.Action("Index","Writer")">List Writers</a></li>
                            <li><a id="btnAddWriter" class="btnAddWriter" href="javascript:void(0)">Add Writer</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="inbox.html" class="waves-effect"><i data-icon=")" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Books</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="@Url.Action("Index","Book")">List Book</a></li>
                            <li><a href="@Url.Action("AddBook","Book")">Add Book</a></li>
                            <li><a href="@Url.Action("BookSuplied","BorrowBook")">Borrowed Books</a></li>
                            <li><a href="@Url.Action("BookDelivered","BorrowBook")">Delivered Books</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="inbox.html" class="waves-effect"><i data-icon=")" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Members</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="@Url.Action("Index","Member")">List Members</a></li>
                            <li><a href="@Url.Action("AddMember","Member")">Add Member</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="@Url.Action("Index","Membership")" class="waves-effect"><i class="linea-icon linea-basic fa-fw" data-icon="q"></i>Membership Operations</a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index","Vote")" class="waves-effect"><i class="linea-icon linea-basic fa-fw" data-icon="q"></i>Vote Book</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- Left navbar-header end -->
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">@ViewBag.Title</h4>
                    </div>
                </div>
                <div class="row white-box">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->
                <footer class="footer text-center"> 2021 &copy; Toros Library System </footer>
            </div>
            <!-- /#page-wrapper -->
        </div>
        <!-- /#wrapper -->
        <!-- jQuery -->
        <script src="~/Scripts/jquery.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/sidebar-nav.min.js"></script>
        <script src="~/Scripts/jquery.slimscroll.js"></script>
        <script src="~/Scripts/waves.js"></script>
        <script src="~/Scripts/jquery.flot.js"></script>
        <script src="~/Scripts/jquery.sparkline.min.js"></script>
        <script src="~/Scripts/jquery.easypiechart.min.js"></script>
        <script src="~/Scripts/easy-pie-chart.init.js"></script>
        <script src="~/Scripts/custom.js"></script>
        <script src="~/Scripts/dashboard2.js"></script>
        <script src="~/Scripts/jQuery.style.switcher.js"></script>
        <script src="~/Scripts/jquery.dataTables.min.js"></script>
        <script src="~/Scripts/dataTables.buttons.min.js"></script>
        <script src="~/Scripts/buttons.flash.min.js"></script>
        <script src="~/Scripts/jszip.min.js"></script>
        <script src="~/Scripts/pdfmake.min.js"></script>
        <script src="~/Scripts/vfs_fonts.js"></script>
        <script src="~/Scripts/buttons.html5.min.js"></script>
        <script src="~/Scripts/buttons.print.min.js"></script>
        <script>
            $(document).ready(function () {
                // Setup - add a text input to each footer cell
                $('#example tfoot th').each(function () {
                    var title = $(this).text();
                    $(this).html('<input type="text" placeholder="Search ' + title + '" />');
                });

                // DataTable
                var table = $('#example').DataTable({
                    dom: 'Bfrtip',
                    buttons: [
                        'copy', 'csv', 'excel', 'pdf', 'print'
                    ]
                });

                //Apply the search
                table.columns().every(function () {
                    var that = this;

                    $('input', this.footer()).on('keyup change clear', function () {
                        if (that.search() !== this.value) {
                            that
                                .search(this.value)
                                .draw();
                        }
                    });
                });
            });
        </script>
        <script src="~/Scripts/sweetalert2.min.js"></script>
        <script src="~/Scripts/main.js"></script>
    @RenderSection("script",false)
    </div>
</body>
</html>