LibraryProject/LibraryProject/Controllers/BorrowBookController.cs
using Library.Data.Model;
using Library.Data.UnitOfWork;
using LibraryProject.SupporterClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryProject.Controllers
{
    [RoleControl]
    public class BorrowBookController : Controller
    {
        UnitOfWork unitofWork;
        public BorrowBookController()
        {
            unitofWork = new UnitOfWork();
        }
        public ActionResult BookSuplied()
        {
            var borrowBook = unitofWork.GetRepository<BorrowBook>().GetAll(x => x.BroughtDate == null);
            return View(borrowBook);
        }

        public ActionResult BookDelivered()
        {
            var borrowBook = unitofWork.GetRepository<BorrowBook>().GetAll(x=>x.BroughtDate != null); //db'de BroughtDate null olmayacagi icin
            return View(borrowBook);
        }

        public ActionResult GiveBook()
        {
            ViewBag.Books = unitofWork.GetRepository<Book>().GetAll( x => x.Number > 0); //kalmamışsa gösterme
            ViewBag.Members = unitofWork.GetRepository<Member>().GetAll();
            return View();
        }

        [HttpPost]
        public JsonResult GiveBookJson(int memberId, int bookId, DateTime bringDate)
        {
            BorrowBook borrowBook = new BorrowBook();
            borrowBook.BorrowDate = DateTime.Now;
            borrowBook.BringDate = bringDate;
            borrowBook.BookId = bookId;
            borrowBook.MemberId = memberId;

            unitofWork.GetRepository<BorrowBook>().Add(borrowBook);
            var situation = unitofWork.SaveChanges();
            if (situation > 0)
                return Json("1");
            else return Json("0");
        }

        public ActionResult UpdateBorrowBook(int borrowBookId)
        {
            ViewBag.Books = unitofWork.GetRepository<Book>().GetAll(x => x.Number > 0); //kalmamışsa gösterme
            ViewBag.Members = unitofWork.GetRepository<Member>().GetAll();
            var borrowBook = unitofWork.GetRepository<BorrowBook>().GetById(borrowBookId);
            return View(borrowBook);
        }

        [HttpPost]
        public JsonResult UpdateBorrowBookJson(int borrowBookId, int memberId, int bookId, DateTime bringDate)
        {
            var borrowBook = unitofWork.GetRepository<BorrowBook>().GetById(borrowBookId);

            borrowBook.BringDate = bringDate; //getireceği tarih
            borrowBook.BookId = bookId;
            borrowBook.MemberId = memberId;

            unitofWork.GetRepository<BorrowBook>().Update(borrowBook);
            var situation = unitofWork.SaveChanges();
            if (situation > 0)
                return Json("1");
            else return Json("0");
        }

        [HttpPost]
        public JsonResult DeliveredMarkJson(int borrowBookId)
        {
            var borrowBook = unitofWork.GetRepository<BorrowBook>().GetById(borrowBookId);
            borrowBook.BroughtDate = DateTime.Now;
            unitofWork.GetRepository<BorrowBook>().Update(borrowBook);
            var situation = unitofWork.SaveChanges();
            if (situation > 0)
                return Json("1");
            else return Json("0");
        }
    }
}

LibraryProject/LibraryProject/Views/BorrowBook/BookDelivered.cshtml
@{
    ViewBag.Title = "Delivered Books";
    DateTime deliverTime;
}
@using Library.Data.Model;
@model List<BorrowBook>

<h2>Delivered Books</h2>


<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Book Name</th>
            <th>Book Borrower Member</th>
            <th>Received Date</th>
            <th>Bring Date</th>
            <th>Delivered Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var borrowBook in Model)
        {
            deliverTime = Convert.ToDateTime(borrowBook.BroughtDate);
        <tr>
            <td>@borrowBook.Book.Name</td>
            <td>@borrowBook.Member.Name</td>
            <td>@borrowBook.BorrowDate.ToString("dddd, dd MMMM yyyy")</td>
            <td>@borrowBook.BringDate.ToString("dddd, dd MMMM yyyy")</td>
            <td>@deliverTime.ToString("dddd, dd MMMM yyyy")</td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Book Name</th>
            <th>Book Borrower Member</th>
            <th>Received Date</th>
            <th>Bring Date</th>
            <th>Delivered Date</th>
        </tr>
    </tfoot>
</table>

LibraryProject/LibraryProject/Views/BorrowBook/BookSuplied.cshtml
@{
    ViewBag.Title = "Borrowed Books";
}
@using Library.Data.Model;
@model List<BorrowBook>

<h2 style="display:inline-block;">Borrowed Books</h2>

<a href="@Url.Action("GiveBook","BorrowBook")" class="borrowBookUpdate btn btn-success" style="float:right">Give a Book</a>
<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Book Name</th>
            <th>Book Borrower Member</th>
            <th>Received Date</th>
            <th>Bring Date</th>
            <th>Update</th>
            <th>Mark as Brought</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var borrowBook in Model)
        {
        <tr>
            <td>@borrowBook.Book.Name</td>
            <td>@borrowBook.Member.Name</td>
            <td>@borrowBook.BorrowDate.ToString("dddd, dd MMMM yyyy")</td>
            <td>@borrowBook.BringDate.ToString("dddd, dd MMMM yyyy")</td>
            <td><a href="@Url.Action("UpdateBorrowBook","BorrowBook", new { borrowBookId = borrowBook.Id})" class="btn btn-danger">Update</a></td>
            <td><button class="markAsBrought btn btn-success" value="@borrowBook.Id">Mark as Brought</button></td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Book Name</th>
            <th>Book Borrower Member</th>
            <th>Received Date</th>
            <th>Bring Date</th>
            <th>Update</th>
            <th>Mark as Brought</th>
        </tr>
    </tfoot>
</table>

LibraryProject/LibraryProject/Views/BorrowBook/GiveBook.cshtml
@{
    ViewBag.Title = "Give a Book";
}

<h2>Give a Book</h2>

<form class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-12">Members</label>
        <div class="col-sm-10">
            <select id="memberId" class="form-control">
                @foreach (var member in ViewBag.Members)
                {
                    <option data-id="@member.Id">@member.Name</option>
                }

            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-12">Books</label>
        <div class="col-sm-12">
            <select id="bookId" class="form-control">
                @foreach (var book in ViewBag.Books)
                {
                    <option data-id="@book.Id">@book.Name</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-12">The Date It Will Bring</label>
        <div class="col-md-12">
            <input id="bringDate" type="date" min="@DateTime.Now.ToString("yyyy-MM-dd")" class="form-control">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <input id="giveBook" type="button" class="btn btn-block btn-info" value="Save" />
        </div>
    </div>
</form>

LibraryProject/LibraryProject/Views/BorrowBook/UpdateBorrowBook.cshtml
@{
    ViewBag.Title = "Update Given Book";
}

@using Library.Data.Model
@model BorrowBook

<h2>Update Given Book</h2>

<form class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-12">Members</label>
        <div class="col-sm-10">
            <select id="memberId" class="form-control">
                @foreach (var member in ViewBag.Members)
                {
                    if (member.Id == Model.MemberId)
                    {
                        <option data-id="@member.Id" selected>@member.Name</option>
                    }
                    else
                    {
                        <option data-id="@member.Id">@member.Name</option>
                    }
                }

            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-12">Books</label>
        <div class="col-sm-12">
            <select id="bookId" class="form-control">
                @foreach (var book in ViewBag.Books)
                {
                    if (book.Id == Model.BookId)
                    {
                        <option data-id="@book.Id" selected>@book.Name</option>
                    }
                    else
                    {
                        <option data-id="@book.Id">@book.Name</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-12">The Date It Will Bring</label>
        <div class="col-md-12">
            <input id="bringDate" type="date" min="@DateTime.Now.ToString("yyyy-MM-dd")" value="@Model.BringDate.ToString("yyyy-MM-dd")" class="form-control">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <input id="updateGivenBook" data-id="@Model.Id" type="button" class="btn btn-block btn-info" value="Save" />
        </div>
    </div>
</form>